services:
  payments-api:
    build: .
    container_name: payments-api
    depends_on:
      - rabbitmq
    environment:
      RabbitMQ__Host: rabbitmq
      RabbitMQ__Username: guest
      RabbitMQ__Password: guest

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
