apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-api
  template:
    metadata:
      labels:
        app: payments-api
    spec:
      containers:
        - name: payments-api
          image: payments-api:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: payments-api-config
            - secretRef:
                name: payments-api-secret
